project:
  type: website
  output-dir: docs
  render:
    - "*.qmd"
    - "!conda_env/"

website:
  title: "CS 1671/2071 Human Language Technologies"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: hw0.qmd
        text: HW0
      - href: hw1.qmd
        text: HW1
      - href: hw2.qmd
        text: HW2
      - href: project.qmd
        text: Project

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



