project:
  type: website
  output-dir: docs
  render:
    - "!conda_env/"

website:
  title: "CS 1671/2071 Human Language Technologies, Spring 2025"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



